-- RoamCollie PostgreSQL schema proposal, v1 (not applied).
-- TWD only; amounts are integer cents. UUIDs are generated by the API.
-- Cross-row totals, permissions and concurrency rules: docs/database-design.md.
BEGIN;

CREATE TABLE users (
  id uuid PRIMARY KEY,
  auth_subject text NOT NULL UNIQUE,
  display_name varchar(80) NOT NULL CHECK (btrim(display_name) <> ''),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE trips (
  id uuid PRIMARY KEY,
  owner_user_id uuid NOT NULL REFERENCES users(id),
  name varchar(120) NOT NULL CHECK (btrim(name) <> ''),
  destination varchar(120),
  start_date date NOT NULL,
  days integer NOT NULL CHECK (days BETWEEN 1 AND 365),
  currency_code varchar(3) NOT NULL DEFAULT 'TWD' CHECK (currency_code = 'TWD'),
  archived_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE trip_members (
  id uuid PRIMARY KEY,
  trip_id uuid NOT NULL REFERENCES trips(id),
  user_id uuid REFERENCES users(id), -- NULL: a guest recorded by an authenticated member
  display_name varchar(80) NOT NULL CHECK (btrim(display_name) <> ''),
  role varchar(10) NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
  sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  left_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (trip_id, id),
  UNIQUE (trip_id, user_id)
);

CREATE TABLE expenses (
  id uuid PRIMARY KEY,
  trip_id uuid NOT NULL REFERENCES trips(id),
  payer_member_id uuid NOT NULL,
  created_by_user_id uuid NOT NULL REFERENCES users(id),
  title varchar(200) NOT NULL CHECK (btrim(title) <> ''),
  category varchar(16) NOT NULL CHECK (category IN ('food', 'transport', 'lodging', 'shopping', 'other')),
  expense_date date NOT NULL,
  amount_cents bigint NOT NULL CHECK (amount_cents BETWEEN 1 AND 10000000000),
  split_mode varchar(10) NOT NULL CHECK (split_mode IN ('equal', 'custom')),
  note text,
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (trip_id, id),
  FOREIGN KEY (trip_id, payer_member_id) REFERENCES trip_members(trip_id, id)
);

CREATE TABLE expense_shares (
  trip_id uuid NOT NULL,
  expense_id uuid NOT NULL,
  member_id uuid NOT NULL,
  amount_cents bigint NOT NULL CHECK (amount_cents BETWEEN 0 AND 10000000000),
  PRIMARY KEY (expense_id, member_id),
  FOREIGN KEY (trip_id, expense_id) REFERENCES expenses(trip_id, id),
  FOREIGN KEY (trip_id, member_id) REFERENCES trip_members(trip_id, id)
);

-- Records of real-world repayments, not computed suggestions or actual money transfers.
CREATE TABLE settlements (
  id uuid PRIMARY KEY,
  trip_id uuid NOT NULL REFERENCES trips(id),
  from_member_id uuid NOT NULL,
  to_member_id uuid NOT NULL,
  amount_cents bigint NOT NULL CHECK (amount_cents BETWEEN 1 AND 10000000000),
  status varchar(12) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'voided')),
  paid_at timestamptz NOT NULL,
  created_by_user_id uuid NOT NULL REFERENCES users(id),
  confirmed_by_user_id uuid REFERENCES users(id),
  confirmed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (from_member_id <> to_member_id),
  CHECK ((confirmed_at IS NULL) = (confirmed_by_user_id IS NULL)),
  CHECK (status <> 'confirmed' OR confirmed_at IS NOT NULL),
  FOREIGN KEY (trip_id, from_member_id) REFERENCES trip_members(trip_id, id),
  FOREIGN KEY (trip_id, to_member_id) REFERENCES trip_members(trip_id, id)
);

CREATE INDEX trips_owner_idx ON trips(owner_user_id);
CREATE INDEX trip_members_user_idx ON trip_members(user_id) WHERE user_id IS NOT NULL;
CREATE INDEX expenses_trip_date_idx ON expenses(trip_id, expense_date DESC, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX expenses_payer_idx ON expenses(trip_id, payer_member_id);
CREATE INDEX shares_member_idx ON expense_shares(trip_id, member_id);
CREATE INDEX settlements_trip_idx ON settlements(trip_id, status, paid_at DESC);
CREATE INDEX settlements_from_idx ON settlements(trip_id, from_member_id);
CREATE INDEX settlements_to_idx ON settlements(trip_id, to_member_id);

COMMIT;
