import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Map,Plus,Receipt,ArrowLeftRight,Users,ChevronDown,ArrowUpRight,CalendarDays,MapPin,Search,X,Utensils,Train,ShoppingBag,BedDouble,MoreHorizontal,Check,Wallet,ArrowRight,Compass,Trash2} from 'lucide-react';
import {splitEqual,balances,settlements} from './ledger';
import './style.css';
const money=n=>new Intl.NumberFormat('zh-TW',{maximumFractionDigits:2}).format(n/100);
const cats={餐飲:Utensils,交通:Train,住宿:BedDouble,購物:ShoppingBag,其他:Receipt};
const today=()=>new Date().toLocaleDateString('sv-SE');
const sample={id:'demo',name:'京都・慢慢走的日子',destination:'日本・京都',start:'2026-11-06',days:5,members:['Willy','小安','Yuki','阿哲'],expenses:[{id:'1',title:'入住町家，開啟京都生活',category:'住宿',date:'2026-11-06',payer:'Willy',cents:1280000,shares:{Willy:320000,小安:320000,Yuki:320000,阿哲:320000},mode:'equal'},{id:'2',title:'京都車站 → 祇園計程車',category:'交通',date:'2026-11-06',payer:'阿哲',cents:68000,shares:{Willy:17000,小安:17000,Yuki:17000,阿哲:17000},mode:'equal'},{id:'3',title:'第一餐！道地日式拉麵',category:'餐飲',date:'2026-11-06',payer:'小安',cents:124000,shares:{Willy:31000,小安:31000,Yuki:31000,阿哲:31000},mode:'equal'},{id:'4',title:'便利商店的宵夜補給',category:'餐飲',date:'2026-11-07',payer:'Yuki',cents:46000,shares:{Willy:16000,Yuki:30000},mode:'custom'}]};
function Avatar({name,i=0}){return <span className={'avatar a'+i%4}>{name.slice(0,1)}</span>}
function Modal({title,onClose,children}){const ref=useRef();useEffect(()=>{const old=document.activeElement;ref.current.showModal();return()=>old?.focus()},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="關閉"><X size={22}/></button></div>{children}</dialog>}
function App(){
 const [trips,setTrips]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem('roamcollie.v1'));return Array.isArray(saved)&&saved.length?saved:[sample]}catch{return [sample]}});
 const [active,setActive]=useState(trips[0].id),[page,setPage]=useState('記帳本'),[modal,setModal]=useState(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('全部'),[toast,setToast]=useState('');
 const trip=trips.find(t=>t.id===active)||trips[0];
 useEffect(()=>{try{localStorage.setItem('roamcollie.v1',JSON.stringify(trips))}catch{setToast('儲存空間不足，請保留此頁面並備份資料。')}},[trips]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(t)}},[toast]);
 const update=t=>setTrips(ts=>ts.map(x=>x.id===t.id?t:x));
 const total=trip.expenses.reduce((s,e)=>s+e.cents,0),balance=balances(trip),transfers=settlements(trip);
 const visible=trip.expenses.filter(e=>(filter==='全部'||e.category===filter)&&e.title.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date));
 const end=new Date(trip.start+'T12:00:00');end.setDate(end.getDate()+trip.days-1);
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('我的行程')}}><img src="/logo.png" alt="RoamCollie 牧羊犬 Logo"/><span>RoamCollie<small>一起出走，輕鬆分帳</small></span></a><div className="side-label">旅行工具箱</div><nav>{[[Map,'我的行程'],[Receipt,'記帳本'],[ArrowLeftRight,'分帳結算'],[Users,'旅伴']].map(([Icon,label])=><button key={label} className={page===label?'nav-item active':'nav-item'} onClick={()=>setPage(label)}><Icon size={20}/>{label}{label==='記帳本'&&<span className="nav-dot"/>}</button>)}</nav><div className="side-trip"><Compass size={25}/><p>好好旅行，<br/>帳交給 RoamCollie。</p><span>每一段旅程，都值得一起。</span><div className="dashed-route"/></div><div className="sidebar-bottom"><span className="local-dot"/> 個人裝置模式<small>資料儲存於此瀏覽器</small></div></aside>
 <div className="workspace"><header className="topbar"><div className="breadcrumb">我的行程 <span>/</span> <strong>{trip.name}</strong></div><div className="top-actions"><span className="saved"><Check size={14}/> 已儲存於此裝置</span><Avatar name="Willy"/></div></header><main><div className="page-heading flex items-center justify-between"><div><div className="eyebrow">讓回憶一起，讓帳目清楚。</div><h1>{page}</h1></div><button className="button secondary" onClick={()=>setModal('trip')}><Plus size={18}/>新增行程</button></div>
 <section className="trip-hero"><div className="hero-content"><span className="trip-tag"><span/> {trip.id==='demo'?'示範行程':'旅程已建立'}</span><h2>{trip.name}</h2><div className="hero-meta"><span><CalendarDays size={16}/>{trip.start.replaceAll('-',' / ')} — {String(end.getMonth()+1).padStart(2,'0')} / {String(end.getDate()).padStart(2,'0')}</span><span>{trip.days} 天 {trip.days-1} 夜</span></div><div className="hero-bottom"><span><MapPin size={16}/>{trip.destination||'目的地待定'}</span><div className="hero-avatars">{trip.members.slice(0,4).map((m,i)=><Avatar key={m} name={m} i={i}/>)}<span>{trip.members.length} 位旅伴</span></div></div></div><div className="hero-caption">把日子走慢一點。<small>Make room for memories.</small></div></section>
 <div className="trip-switch"><label htmlFor="trip-select">目前行程</label><select id="trip-select" value={trip.id} onChange={e=>setActive(e.target.value)}>{trips.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div>
 {page==='我的行程'?<section className="trip-grid">{trips.map(t=><button className="trip-card" key={t.id} onClick={()=>{setActive(t.id);setPage('記帳本')}}><MapPin/><h3>{t.name}</h3><p>{t.start} · {t.days} 天 · {t.members.length} 人</p><span>打開記帳本 <ArrowRight size={16}/></span></button>)}<button className="trip-card new-trip" onClick={()=>setModal('trip')}><Plus/><h3>下一站，去哪裡？</h3><p>建立一段新的旅程</p></button></section>:<>
 <section className="stats"><div><span><Wallet size={17}/>旅程總支出</span><strong><small>NT$</small> {money(total)}</strong><p>共 {trip.expenses.length} 筆旅途紀錄</p></div><div><span><Users size={17}/>每人平均支出</span><strong><small>NT$</small> {money(Math.round(total/trip.members.length))}</strong><p>依 {trip.members.length} 位旅伴計算，實際依分帳設定</p></div><div className="stat-green"><span><ArrowLeftRight size={17}/>待結算金額</span><strong><small>NT$</small> {money(Object.values(balance).filter(n=>n>0).reduce((a,b)=>a+b,0))}</strong><button onClick={()=>setPage('分帳結算')}>查看旅伴間的分帳 <ArrowUpRight size={16}/></button></div></section>
 <div className="content-grid"><section className="ledger-panel"><div className="panel-heading"><div><h2>{page==='分帳結算'?'分帳結算':page==='旅伴'?'這次一起出發的人':'旅途中的每一筆'}</h2><p>{page==='記帳本'?'把小事記下來，把時間留給風景。':'每一筆分攤，都清清楚楚。'}</p></div>{page==='記帳本'&&<button className="button primary" onClick={()=>setModal('expense')}><Plus size={18}/>新增支出</button>}</div>
 {page==='記帳本'?<><div className="ledger-tools"><div className="filters">{['全部','餐飲','交通','住宿','購物','其他'].map(c=><button key={c} onClick={()=>setFilter(c)} className={filter===c?'selected':''}>{c}</button>)}</div><div className="search"><Search size={17}/><input aria-label="搜尋支出" placeholder="搜尋支出" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="expense-list">{visible.length===0?<div className="empty"><Receipt size={32}/><h3>{trip.expenses.length?'沒有符合的支出':'第一筆回憶，從這裡開始'}</h3><p>{trip.expenses.length?'試試其他分類或關鍵字。':'點選「新增支出」，記下旅途中的花費。'}</p></div>:visible.map((e,i)=>{const Icon=cats[e.category];return <React.Fragment key={e.id}>{(i===0||visible[i-1].date!==e.date)&&<div className="date-heading">{e.date.replaceAll('-',' / ')}<span>{visible.filter(x=>x.date===e.date).length} 筆支出</span></div>}<button className="expense-row" onClick={()=>setModal(e)}><span className={'category-icon cat-'+e.category}><Icon size={21}/></span><span className="expense-copy"><strong>{e.title}</strong><small>{e.payer} 先付款 <span>·</span> {e.mode==='equal'?`${Object.keys(e.shares).length} 人平均分帳`:'指定金額分帳'}</small></span><span className="expense-amount">NT$ {money(e.cents)}<small>{e.category}</small></span></button></React.Fragment>})}</div><div className="ledger-footer"><Check size={14}/> 每一筆小花費，都是一起旅行的痕跡。</div></>:page==='分帳結算'?<div className="settlements"><p className="notice">以下為建議轉帳方式；實際付款請由旅伴自行完成。</p>{transfers.length?transfers.map((t,i)=><div className="transfer" key={i}><span>{t.from} <ArrowRight size={16}/> {t.to}</span><strong>NT$ {money(t.cents)}</strong></div>):<div className="empty"><Check/><h3>帳目已平衡</h3><p>目前沒有需要轉帳的金額。</p></div>}</div>:<div className="members-list">{trip.members.map((m,i)=><div key={m}><Avatar name={m} i={i}/><strong>{m}</strong><span>已先付 NT$ {money(trip.expenses.filter(e=>e.payer===m).reduce((s,e)=>s+e.cents,0))}</span></div>)}</div>}
 </section><aside className="right-rail"><section className="companions"><div className="rail-title"><h3>旅伴分帳概況</h3><span>{trip.members.length} 人</span></div>{trip.members.map((m,i)=><div className="member-balance" key={m}><Avatar name={m} i={i}/><span>{m}<small>{balance[m]>0?'應收款項':balance[m]<0?'應付款項':'已平衡'}</small></span><strong className={balance[m]>0?'positive':''}>{balance[m]>0?'+':balance[m]<0?'−':''}{money(Math.abs(balance[m]))}</strong></div>)}<button className="rail-link" onClick={()=>setPage('分帳結算')}>查看完整結算 <ArrowRight size={16}/></button></section><section className="collie-note"><img src="/logo.png" alt=""/><div><h3>玩得開心，分得明白。</h3><p>先付款的人記一筆，<br/>剩下的讓 Collie 幫你算。</p></div></section></aside></div></>}
 <footer>RoamCollie <span>陪你走遠一點，也靠近一點。</span><small>目前以新臺幣 TWD 記帳</small></footer></main></div>
 <nav className="mobile-nav">{[[Map,'我的行程'],[Receipt,'記帳本'],[ArrowLeftRight,'分帳結算'],[Users,'旅伴']].map(([Icon,label])=><button key={label} className={page===label?'active':''} onClick={()=>setPage(label)}><Icon size={21}/><span>{label}</span></button>)}</nav>
 {toast&&<div role="status" className="toast"><Check size={18}/>{toast}</div>}
 {modal==='trip'&&<TripForm onClose={()=>setModal(null)} onSave={t=>{setTrips([...trips,t]);setActive(t.id);setPage('記帳本');setModal(null);setToast('行程已建立，邀旅伴一起出發吧！')}}/>}
 {modal==='expense'&&<ExpenseForm trip={trip} onClose={()=>setModal(null)} onSave={e=>{update({...trip,expenses:[...trip.expenses,e]});setModal(null);setToast('支出已儲存，分帳也算好了')}}/>}
 {modal&&typeof modal==='object'&&<Modal title="支出明細" onClose={()=>setModal(null)}><div className="detail"><h3>{modal.title}</h3><div className="detail-total">NT$ {money(modal.cents)}</div><p>{modal.date} · {modal.category} · {modal.payer} 先付款</p><h4>分攤金額</h4>{Object.entries(modal.shares).map(([m,n])=><div className="transfer" key={m}><span>{m}</span><strong>NT$ {money(n)}</strong></div>)}<button className="button danger" onClick={()=>{if(window.confirm('確定刪除這筆支出？')){update({...trip,expenses:trip.expenses.filter(e=>e.id!==modal.id)});setModal(null);setToast('支出已刪除')}}}><Trash2 size={17}/>刪除支出</button></div></Modal>}
 </div>
}
function TripForm({onClose,onSave}){const [error,setError]=useState('');return <Modal title="建立新的旅程" onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),members=f.get('members').split(/[,，、\n]/).map(s=>s.trim()).filter(Boolean);if(!members.length||new Set(members).size!==members.length)return setError('請填入旅伴姓名，每位旅伴的名稱不可重複。');if(!f.get('name').trim())return setError('請輸入行程名稱。');onSave({id:crypto.randomUUID(),name:f.get('name').trim(),destination:f.get('destination').trim(),start:f.get('start'),days:Number(f.get('days')),members,expenses:[]})}}><label>行程名稱<input name="name" placeholder="例如：京都・慢慢走的日子" required maxLength={60}/></label><label>目的地<input name="destination" placeholder="例如：日本・京都" maxLength={60}/></label><div className="form-grid grid grid-cols-2"><label>出發日期<input type="date" name="start" required defaultValue={today()}/></label><label>旅遊天數<input type="number" name="days" defaultValue="3" min="1" max="365" required/></label></div><label>旅伴姓名<textarea name="members" rows="3" placeholder="Willy、小安、Yuki、阿哲" required/><small>包含自己，使用逗號、頓號或換行分隔。</small></label>{error&&<p className="error" role="alert">{error}</p>}<button className="button primary full" type="submit"><Plus size={18}/>建立行程</button></form></Modal>}
function ExpenseForm({trip,onClose,onSave}){const [mode,setMode]=useState('equal'),[selected,setSelected]=useState(trip.members),[amount,setAmount]=useState(''),[custom,setCustom]=useState({}),[error,setError]=useState('');const cents=Math.round(Number(amount)*100),sum=selected.reduce((s,m)=>s+Math.round(Number(custom[m]||0)*100),0);return <Modal title="記下這筆支出" onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!f.get('title').trim())return setError('請輸入支出名稱。');if(!Number.isSafeInteger(cents)||cents<=0||cents>10000000000)return setError('請輸入有效金額，最高為一億元。');if(!selected.length)return setError('請至少選擇一位分帳旅伴。');if(mode==='custom'&&sum!==cents)return setError('指定分攤金額的合計必須等於支出總額。');const shares=mode==='equal'?splitEqual(cents,selected):Object.fromEntries(selected.map(m=>[m,Math.round(Number(custom[m]||0)*100)]));onSave({id:crypto.randomUUID(),title:f.get('title').trim(),cents,payer:f.get('payer'),date:f.get('date'),category:f.get('category'),mode,shares})}}><label>支出名稱<input name="title" placeholder="這一筆花在什麼地方？" required maxLength={100}/></label><label>總金額（TWD）<input className="amount-input" type="number" inputMode="decimal" min="0.01" max="100000000" step="0.01" required placeholder="0.00" value={amount} onChange={e=>setAmount(e.target.value)}/></label><div className="form-grid grid grid-cols-2"><label>誰先付款？<select name="payer">{trip.members.map(m=><option key={m}>{m}</option>)}</select></label><label>支出分類<select name="category">{Object.keys(cats).map(c=><option key={c}>{c}</option>)}</select></label></div><label>支出日期<input name="date" type="date" defaultValue={today()} required/></label><fieldset><legend>如何分帳？</legend><div className="split-tabs"><button type="button" className={mode==='equal'?'selected':''} onClick={()=>setMode('equal')}>平均分帳</button><button type="button" className={mode==='custom'?'selected':''} onClick={()=>setMode('custom')}>指定金額</button></div>{trip.members.map((m,i)=><div className="split-member" key={m}><label><input type="checkbox" checked={selected.includes(m)} onChange={e=>setSelected(e.target.checked?[...selected,m]:selected.filter(x=>x!==m))}/><Avatar name={m} i={i}/>{m}</label>{mode==='custom'?<input aria-label={`${m} 分攤金額`} type="number" inputMode="decimal" min="0" step="0.01" max="100000000" disabled={!selected.includes(m)} value={custom[m]||''} placeholder="0.00" onChange={e=>setCustom({...custom,[m]:e.target.value})}/>:<span>NT$ {selected.includes(m)&&Number.isSafeInteger(cents)&&cents>0?money(splitEqual(cents,selected)[m]):'0'}</span>}</div>)}{mode==='custom'&&<p className="notice">已分配 NT$ {money(sum)} ／ 總額 NT$ {money(cents||0)}</p>}</fieldset>{error&&<p className="error" role="alert">{error}</p>}<button type="submit" className="button primary full"><Check size={18}/>儲存支出</button></form></Modal>}
createRoot(document.getElementById('root')).render(<App/>);
